In [7]:
import numpy as np
x=np.array([45,6,7.8,"me",True])
y=np.array([45,6,9])
z=np.array([True])
print("",x,"\n",type(x),"\n",type(y),"\n",type(z))
print("",x.dtype,"\n",y.dtype,"\n",z.dtype)

 ['45' '6' '7.8' 'me' 'True'] 
 <class 'numpy.ndarray'> 
 <class 'numpy.ndarray'> 
 <class 'numpy.ndarray'>
 <U32 
 int32 
 bool


In [17]:
a=np.array([[20,56,89],[69,43,87],[67,43,80]])
print("",a,"\n",type(a),"\n",a.shape)


 [[20 56 89]
 [69 43 87]
 [67 43 80]] 
 <class 'numpy.ndarray'> 
 (3, 3)


In [18]:
a.reshape(3,3)

array([[20, 56, 89],
       [69, 43, 87],
       [67, 43, 80]])

In [21]:
ar=np.arange(5,20+1)
ar


array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [35]:
np.around([4.4435,24.98],1)

array([ 4.4, 25. ])

In [40]:
print(np.around(np.sqrt([4.52788,6.9992872]),4))
print(np.square([4.545,56.777]))


[2.1279 2.6456]
[  20.657025 3223.627729]


In [61]:
a6=np.array([[34,35,77],[2,6,np.NaN]])
print(a6)

acopy=a6.astype(str)
print(acopy)




[[34. 35. 77.]
 [ 2.  6. nan]]
[['34.0' '35.0' '77.0']
 ['2.0' '6.0' 'nan']]
