In [2]:
import pandas as pd

In [6]:
d=[1,2,3,4,5]

res=pd.Series(d) #using default index
print(res)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [7]:
d=[1,2,3,4,5]
i=["A","B","C","D","E"]
res=pd.Series(d,index=i) #using custom index
print(res)


A    1
B    2
C    3
D    4
E    5
dtype: int64


In [20]:
d={'a':1,'b':2,'c':3,'d':4,'e':5}
d1=dict([('a',45),('b',46)])
dc=d1.copy()

print('',d1,'\n',d)
ser=pd.Series(dc)
print(ser)

#pd.Series(d)

 {'a': 45, 'b': 46} 
 {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
a    45
b    46
dtype: int64


In [21]:
ser.replace(46,69)

a    45
b    69
dtype: int64

In [23]:
import numpy as np
dat=np.array([3746,328,287,5498])
ser1=pd.Series(dat,index=['a','b','c','d'])
print(ser1)


a    3746
b     328
c     287
d    5498
dtype: int32


In [31]:
dat={'name':['Tony','Peter','Cap'],'Age':[60,28,120]}
df=pd.DataFrame(dat,index=['1','2','3'])
print(df)



    name  Age
1   Tony   60
2  Peter   28
3    Cap  120


In [33]:
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
df=pd.DataFrame(ar,columns=['a','b','c'],index=[1,2,3])
print(df)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
   a  b  c
1  1  2  3
2  4  5  6
3  7  8  9


In [35]:
dat=[['Tony',60],['Cap',120],['Peter',27]]
print(dat)
df=pd.DataFrame(dat,columns=["Name","Age"])
print(df)




[['Tony', 60], ['Cap', 120], ['Peter', 27]]
    Name  Age
0   Tony   60
1    Cap  120
2  Peter   27
